#!/bin/bash

#Config file location
listpath="/home/$USER/.config/play/"
config="$listpath"config
games="$listpath"games.list

if ! [ -f $config ] ; then
	echo "Config file not found at \"$config\""
	exit
fi

#Vars/arrs used for script
gamecmd="$1"
prgm=""
line=""
pathf=""
ctr=0
appID=0
taskname=""
result=""
task=""
ip=`cat $config | sed -n -e 's/^.*ip=//p'`
wr=`cat $config | sed -n -e 's/^.*wr=//p'`
display=`cat $config | sed -n -e 's/^.*display=//p'`
ControlMyMonitor=`cat $config | sed -n -e 's/^.*ControlMyMonitor=//p'`
ControlMyMonitor=${ControlMyMonitor//\\//}
declare -a short
declare -a long
declare -a path
declare -a servicename

#Shortcut locations to make adding games easier
STEAM="steam://rungameid/"
DESKTOP=`cat $config | sed -n -e 's/^.*desktop=//p'`
APPDATA=`cat $config | sed -n -e 's/^.*appdata=//p'`

function check_for_duplicate()
{
	ctr=0

	#Set delimited to comma
	IFS=','

	while IFS= read -r line; do
		read -a strarr <<< "$line"

		for (( n=0; n < ${#strarr[*]}; n++)); do
			if [ "${strarr[n]}" == "$1" ]; then
				get_record $ctr "$line"
				echo -e "Duplicate entry for \""$1"\" found:"
				echo
				print_verbose_header
				echo
				pathf="${path[$ctr]}"
				format_pathf
      				print_verbose_record "${short[$ctr]}" "${long[$ctr]}" "$pathf" "${servicename[$ctr]}"

				exit
			fi
		done
		((ctr++))
	done < $games
}
function format_pathf()
{
	pathf="${pathf//\"/}"
	pathf="${pathf//%STEAM%/$STEAM}"
	pathf="${pathf//%DESKTOP%/$DESKTOP}"
	pathf="${pathf//%APPDATA%/$APPDATA}"
}
function get_record()
{
	short[$1]=$(echo "$2" | grep -Po '([^,]+)' | head -1)
	long[$1]=$(echo "$2" | grep -Po '([^,]+)' | head -2 | tail -1)
	path[$1]=$(echo "$2" | grep -Po '([^,]+)' | head -3 | tail -1)
	servicename[$1]=$(echo "$2" | grep -Po '([^,]+)' | head -4 | tail -1)
}
function print_normal_header()
{
	printf "%-10s           %-25s\n" "Command" "Game Title"
        echo -n "--------------------------------"
}
function print_verbose_header()
{
	printf "%-10s           %-25s      %-46s          %s\n" "Command" "Game Title" "Path" "Task Name"
        echo -n "--------------------------------------------------------------------------------------------------------------------------"

}
function print_normal_record()
{
	printf "%-15s|     %-25s\n" "$1" "$2"
}
function print_verbose_record()
{
	printf "%-15s|     %-25s|     %-50s|     %s\n" "$1" "$2" "$3" "$4"
}
function list_games()
{
        for (( IFS=" " i=0; i<$ctr; i++ )); do
                print_normal_record "${short[i]}" "${long[i]}"
        done
	echo
}
function list_games_verbose()
{
        for (( IFS=" " i=0; i<$ctr; i++ )); do
		#Remove/replace backslash, quote marks, and path shortcuts from path and print result in table
		pathf="${path[i]//\\/}"
		format_pathf
      		print_verbose_record "${short[i]}" "${long[i]}" "$pathf" "${servicename[i]}"
        done
	echo
}
function run_game()
{
	echo "Changing monitor input and launching winrun with parameters \"start $1\""
	sudo chmon $display
	winrun "start $1"

	while [[ 1 ]]; do
		if [[ $(winrun "tasklist /fi \"SESSIONNAME eq CONSOLE\" /fo list" | grep -i $task) == "" ]]; then
			echo "No longer seeing $task running on Window system, changing display input."
			winrun "run $ControlMyMonitor /SetValue \\\\.\DISPLAY1\Monitor0 60 4"
			break;
		fi
	done
}

#Load games from games.list file
if [ -f $games ]; then

	#Read games list
	while IFS= read -r line; do
		short[$ctr]=$(echo $line | awk -F, '{print $1}')
		long[$ctr]=$(echo $line | awk -F, '{print $2}')
		path[$ctr]=$(echo $line | awk -F, '{print $3}')
		servicename[$ctr]=$(echo $line | awk -F, '{print $4}')
		((ctr++))
	done < $games
else
	#Make games list file if it does not exist
	echo $games file  not found, creating!
	touch $games
fi

#Check for script arguments
while [ "$#" != "" ]
do
	case "$1" in
		-l)#List games

			if [ "$2" ]; then
				echo -e "Detected arguments after \""$1"\". Ignoring, as these are not used...\n"
			fi

			print_normal_header
			list_games | sort
			break;;

		-lv)#Display games list with more info
			
			if [ "$2" ]; then
				echo -e "Detected arguments after \""$1"\". Ignoring, as these are not used...\n"
			fi

                        print_verbose_header
			list_games_verbose | sort
                        break;;

		-f)#Find for parameter and display

			if [ ! "$2" ]; then
				echo "No search parameter detected!"
				break
			fi
			if [ "$3" ]; then
				echo -e "Detected arguments after \""$2"\". Ignoring, as these are not used...\n"
			fi

			print_normal_header
			echo
			list_games | grep -i "$2" | sort
			break;;

		-fv)#Find for parameter and display with more info

			if [ ! "$2" ]; then
				echo "Missing search parameter!"
				break
			fi
			if [ "$3" ]; then
				echo -e "Detected arguments after \""$2"\". Ignoring, as these are not used...\n"
			fi

			print_verbose_header
			echo
 			list_games_verbose | grep -i "$2" | sort
			break;;

		-a)#Add game to lis

			if [ ! "$2" ]; then
				echo "Missing program command string!"
				break

				elif [ ! "$3" ]; then
					echo "Missing program title!"
					break

					elif [ ! "$4" ]; then
						echo "Missing program path!"
						break

						elif [ ! "$5" ]; then
							echo "Missing program task name!"
							break
			fi
			if [ "$6" ]; then
				echo -e "Detected arguments after \""$5"\". Ignoring, as these are not used...\n"
			fi

			#Check for duplicate entry
			check_for_duplicate "$2" "$line" $ctr
			check_for_duplicate "$3" "$line" $ctr
			check_for_duplicate "$4" "$line" $ctr
			check_for_duplicate "$5" "$line" $ctr

			#If no duplicate is found, add entry
			if [ ! $match ]; then
				pathf="${4//\\//}"
				echo ""$2","$3","$pathf","$5"" >> "$games"
				echo "Added the following record:"
				echo
				print_verbose_header
				echo
				format_pathf
      				print_verbose_record "$2" "$3" "$pathf" "$5"
			fi

			break;;

		-r)#Attempt to remove game from list

			if [ ! "$2" ]; then
				echo "Missing search parameter!"
				break
			fi
			if [ "$3" ]; then
				echo -e "Detected arguments after \""$3"\". Ignoring, as these are not used...\n"
			fi

			ctr=0
			while IFS= read -r line; do
				if [[ -n $(echo $line | grep "$2") ]]; then
					match=1

					get_record $ctr "$line"
					sed -i "/$2/d" $games

					echo "Removed the following record:"
					echo
					print_verbose_header
					echo
					pathf="${path[$ctr]}"
					format_pathf
      					print_verbose_record "${short[$ctr]}" "${long[$ctr]}" "$pathf" "${servicename[$ctr]}"
					break
				fi
				((ctr++))
			done < $games


			if [ ! $match ]; then
				echo -e "Did not find match for \""$2"\" in \"$games\""
			fi
			break;;

		-? | --help)#Print help text

			if [ "$2" ]; then
				echo -e "Detected arguments after \""$1"\". Ignoring, as these are not used...\n"
			fi

			echo -e "Launch program on remote Windows PC and change monitor inputs automatically.\n"
			echo -e "USAGE"
			echo -e "-----"
			echo -e
			echo -e "\e[3mplay [COMMAND]\e[0m"
			echo -e "Launch the game defined by the COMMAND parameter.\n"
			echo -e "\e[3mplay -l\e[0m"
			echo -e "Print a formatted table of games saved to the games.list file excluding file paths.\n"
			echo -e "\e[3mplay -lv\e[0m"
                        echo -e "Print a formatted table of games saved to the games.list file including file paths and task names.\n"
			echo -e "\e[3mplay -f [PATTERN]\e[0m"
			echo -e "Search for a matching PATTERN in the games.list file and list results excluding file paths.\n"
			echo -e "\e[3mplay -fv [PATTERN]\e[0m"
                        echo -e "Search for a matching PATTERN in the games.list file and list results including file paths and task names.\n"
			echo -e "\e[3mplay -a [COMMAND] [TITLE] [PATH] [TASK]\e[0m"
			echo -e "Add a game to the list that is located at the PATH on the Windows machine, is started by using the COMMAND parameter, and can be easily referenced in the -l functionality by the game's formal TITLE, which shows up in task manager as TASK (typically a \".exe\" file).\n"
			echo -e "\tFilepath shortcuts for PATH"
			echo -e "\t---------------------------"
			printf  "\t%-10s %-1s %-50s\n" "%STEAM%" "=" "$STEAM"
			printf  "\t%-10s %-1s %-50s\n" "%DESKTOP%" "=" "$DESKTOP"
			printf  "\t%-10s %-1s %-50s\n\n" "%APPDATA%" "=" "$APPDATA"
			echo -e "\e[3mplay -r [PATTERN]\e[0m"
			echo -e "Search for a matching PATTERN in the games.list file and remove it from the games.list file.\n"
			echo -e "\e[3mplay -?\e[0m OR \e[3mplay --help\e[0m"
			echo -e "Print this help text.\n"
			break;;

		*)#Search for matching game

			if [ "$2" ]; then
				echo -e "Detected arguments after \""$1"\". Ignoring, as these are not used...\n"
			fi

			echo -n "Checking if \""$1"\" matches a known game in games.list... "
			shopt -s nocasematch
			for (( i=0; i<$ctr; i++ )); do
				if [[ "$1" == "${short[i]}" ]]; then
					path[i]="${path[i]//%STEAM%/$STEAM}"
					path[i]="${path[i]//%DESKTOP%/$DESKTOP}"
					path[i]="${path[i]//%APPDATA%/$APPDATA}"
					prgm="${path[i]}"
					task="${servicename[i]}"
					break
				fi
			done
			shopt -u nocasematch

			#If there was a match, run program. Otherwise, run first arg as is.
			if [ "$prgm" != "" ]; then
				echo "Found!"
				run_game "$prgm"
			else
				echo "Not found!"
				run_game "$1"
			fi

			break;;
	esac
	shift
done
